### ISSUE TITLE
Register this provider in the Pulumi Registry

### ISSUE THREAD

**Issue by ringods** [pulumiverse/pulumi-sentry#5]
Your provider is published in the different package registries, but it is not yet to be found on the [Pulumi Registry](https://www.pulumi.com/registry/). If you want to see this happen, go over to the [pulumi/registry](https://github.com/pulumi/registry) repository and submit a PR with a commit similar to this one:

https://github.com/pulumi/registry/commit/9f582dab4797be0a13185e6fde23a024fb452b4f

**Comment by henriiik** [comment]
i can take a look

**Comment by xiongchiamiov** [comment]
I assume this is why [the documentation link](https://www.pulumi.com/registry/packages/sentry/api-docs/) doesn't work?

**Comment by henriiik** [comment]
I have opened a PR for this https://github.com/pulumi/registry/pull/1635

**Comment by henriiik** [comment]
the PR has been merged, thanks @ringods 🎉
